name: Build and Push

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build.yaml"
      - "noto-cjk/Dockerfile"
      - "CHROME_VERSION"

env:
  DOCKER_IMAGE: ghcr.io/nonchan7720/headless-chrome

jobs:
  setup-build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load version
        run:
          echo "VERSION=$(cat CHROME_VERSION)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container Build and Push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}-noto-cjk
          file: noto-cjk/Dockerfile
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          outputs: type=registry
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
